dist: trusty
language: php

php:
  - 7.2
  - 7.3
  - 7.4

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - sudo pecl install v8js
  - echo "extension = v8js.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit

